using System.ComponentModel.DataAnnotations;

namespace ControlSpending.Models;

public class Person
{
    /// <summary>
    // Class representing a person.
    // The ID will be automatically generated by the database.
    // The int type was used because it occupies less storage space
    // than a GUID. Possible problems related to unauthorized access or
    // the discovery of other records should be handled through
    // authentication, authorization, and access control.

    // The string type property receives the ? operator because initially
    // it not have a value, allowing it to receive null.
    /// </summary>

    [Key] //DataAnnotation to specify that the id will be the primary key
    public int Id { get; set; }

    [Required(ErrorMessage = "Nome é obrigatório")]
    [MaxLength(50, ErrorMessage = "Nome precisa ter no máximo 50 caracteres")]
    public string Name { get; set; } = string.Empty;

    [Range(1, 120, ErrorMessage = "A idade deve estar entre 1 e 120 anos.")]
    public int Age { get; set; }

    /// <summary>
    /// Gets the transactions related to the person.
    /// </summary>
    public ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}