
public class Person{
    /// <summary>
    // Class representing a person.
    // The ID will be automatically generated by the database.
    // The int type was used because it occupies less storage space
    // than a GUID. Possible problems related to unauthorized access or
    // the discovery of other records should be handled through
    // authentication, authorization, and access control.

    // The string type property receives the ? operator because initially
    // it not have a value, allowing it to receive null.
    /// </summary>
    public int Id { get; set; }

    public string? Name { get; set; } 

    public int Age { get; set; }
}