using System.ComponentModel.DataAnnotations;

namespace ControlSpending.Models;

/// <summary>
/// Represents a person who owns financial transactions in the household.
/// </summary>
public class Person
{
    /// <summary>
    /// Gets the identifier generated by the database.
    /// </summary>
    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "Nome é obrigatório")]
    [MaxLength(50, ErrorMessage = "Nome precisa ter no máximo 50 caracteres")]
    public string Name { get; set; } = string.Empty;

    [Range(1, 120, ErrorMessage = "A idade deve estar entre 1 e 120 anos.")]
    public int Age { get; set; }

    /// <summary>
    /// Gets the transactions related to the person. The relationship is configured
    /// with cascade deletion so they are removed when the person is deleted.
    /// </summary>
    public ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}